@startuml
title Diagramme de cas d'utilisation - Bibliotheque

left to right direction

actor "Bibliothecaire" as BIB
actor "Utilisateur" as UTI
actor "Etudiant" as ETU
actor "Enseignant" as ENS

UTI <|-- ETU
UTI <|-- ENS

rectangle "Gestion bibliotheque" {
usecase "connexion" as UC_CO
usecase "creer_utilisateur" as UC_CU
usecase "trouver_un_utilisateur" as UC_TU
usecase "lister_les_retards" as UC_LR
usecase "enregistrer_ouvrage" as UC_EO
usecase "rechercher_simple" as UC_RS
usecase "rechercher_avancee" as UC_RA
usecase "recherche_exemplaire" as UC_RX
usecase "lister_emprunts_utilisateur" as UC_LEU
usecase "lister_ses_emprunts" as UC_LSE
usecase "emprunter_un_ouvrage" as UC_EU
}

BIB --> UC_CU
BIB --> UC_TU
BIB --> UC_LR
BIB --> UC_EO
BIB --> UC_RS
BIB --> UC_RA
BIB --> UC_LEU

UTI --> UC_RS
UTI --> UC_RA
UTI --> UC_LSE
UTI --> UC_EU

UC_CU ..> UC_CO : <<include>>
UC_TU ..> UC_CO : <<include>>
UC_EO ..> UC_CO : <<include>>
UC_LEU ..> UC_TU : <<include>>
UC_LSE ..> UC_CO : <<include>>
UC_EU ..> UC_CO : <<include>>

UC_RS ..> UC_RX : <<extend>>
UC_RA ..> UC_RX : <<extend>>
@enduml
