name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: back/go.mod
          cache-dependency-path: back/go.sum
      - name: Download dependencies
        working-directory: back
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: back
