name: Tests

on:
  workflow_call:

jobs:
  tests-back:
    name: Tests unitaires (Go)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: back/go.mod

      - name: Download dependencies
        working-directory: back
        run: go mod download

      - name: Run tests unitaires
        working-directory: back
        run: go test ./test/...

  tests-tu-front:
    name: Tests unitaires (Mocha)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run tests unitaires Mocha
        working-directory: front
        run: npm run test:mocha
